lylTicket/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import *

urlpatterns = [
    url(r'^$', index),
    url(r'^admin/', admin.site.urls),
    url(r'^trainManage/', include('trainManage.urls')),
    url(r'^ticketQuery/', include("ticketQuery.urls")),
    url(r'^accounts/', include('userClass.urls')),
    url(r'^addPassenger/',include('addPassenger.urls')),

]

trainManage/urls.py
from django.conf.urls import url, include
#from . import views
from .views import *

urlpatterns = [
#        url(r'^add_train/$', add_train, name = "add_train"),
        url(r'^$', train_ListView.as_view(), name = "train_list"),
        url(r'^create/$', train_create.as_view(), name = "train_create"),
        url(r'^detail/(?P<pk>[\w]+)$', train_detail.as_view(), name="train_detail"),
        url(r'^delete/(?P<pk>[\w]+)$', train_delete.as_view(), name="train_delete"),
        url(r'^addCarriage/(?P<pk>[\w]+)$', addCarriage.as_view(), name="train_delete"),
        url(r'^trainCreateFromFile/$', trainCreateFromFile, name="train_create_file"),
        url(r'^updateSeat/$', updateSeat, name="updateSeat"),
        ]

trainManage/models.py
#-*- coding:utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Train(models.Model):
    train_id = models.CharField('列车编号',max_length=5, primary_key=True)
    train_type = models.CharField('列车类型',max_length=1, default="K")
    num_station = models.IntegerField('总站点数',default=0)
    distance = models.FloatField('总里程数', default=0)

    def __str__(self):
        return self.train_id

    def __unicode__(self):
        return self.train_id

class Station(models.Model):
    station_id = models.IntegerField(default = 0, primary_key=True)
    station_name = models.CharField("途经车站", max_length=20)
    station_city = models.CharField("所属城市", max_length=20)

    def __str__(self):
        return self.station_name

    def __unicode__(self):
        return self.station_name


class Run(models.Model):
    @staticmethod
    def generateRunKey(station_id, train_id):
        run_key = '{:X<5}'.format(train_id) + '{:0>5}'.format(station_id)
        return run_key

    run_key = models.CharField(max_length=30, primary_key=True)
    station_name = models.ForeignKey(Station, on_delete=models.CASCADE)
    train_come_by = models.ForeignKey(Train, on_delete=models.CASCADE)
    order_of_station = models.IntegerField(default = 1)
    arrive_time = models.TimeField("到站时间", max_length = 10)
    distance_count = models.FloatField("里程数")
    count_over_night = models.IntegerField(default = -1)

    def __str__(self):
        return self.station_name

    def __unicode__(self):
        return self.run_key

    class Meta:
        ordering = ["train_come_by", "order_of_station"]

class Carriage(models.Model):
    @staticmethod
    def generateCarriageKey(train_id, carriage_id):
        carriage_key = '{:X<5}'.format(train_id) \
                   + '{:0>2}'.format(carriage_id)
        return carriage_key

    seat_type_list = (
        ('shangwu', '商务座'),
        ('yideng', '一等座'),
        ('erdeng', '二等座'),
        ('ruanwo', '软卧'),
        ('yingwo', '硬卧'),
        ('yingzuo', '硬座'),
    )
    carriage_key = models.CharField(max_length=30, primary_key = True)
    train_id = models.ForeignKey(Train, on_delete=models.CASCADE)
    carriage_id = models.IntegerField(default=1)
    num_seat = models.IntegerField(default=0)
    seat_type = models.CharField(max_length=10, choices = seat_type_list)

    def __str__(self):
        return self.carriage_key

    def __unicode__(self):
        return self.carriage_key


class TimeSpan(models.Model):
    time = models.DateField(primary_key=True)

class Seat(models.Model):
    @staticmethod
    def generateSeatRunKey(date, carriage_key, seat_id):
        seat_key = carriage_key \
                + date.time.strftime("%Y%m%d") \
                + '{:0>3}'.format(seat_id)
        return seat_key

    seat_key = models.CharField(max_length=30, primary_key=True)
    carriage = models.ForeignKey(Carriage, on_delete=models.CASCADE)
    seat_id = models.IntegerField()
    date = models.ForeignKey(TimeSpan)
    status = models.CharField(max_length=100)

    def __str__(self):
        return str(self.carriage.carriage_id) + str(self.date.time) \
               + str(self.seat_id)

    def __unicode__(self):
        return str(self.carriage.carriage_id) + str(self.date.time) \
               + str(self.seat_id)
    class Meta:
        ordering = ["seat_key", "date"]


class Price(models.Model):
    train_type = models.CharField('列车类型',max_length=20)
    seat_type = models.CharField('座位类型',max_length=20)
    ratio_student = models.FloatField('学生票打折系数',default=1)
    price_per_km = models.FloatField('每公里计价',default=0.5)

    def __str__(self):
        return self.train_type+" "+self.seat_type+" "+str(self.ratio_student)+" "+str(self.price_per_km)

    def __unicode__(self):
        return self.train_type+" "+self.seat_type+" "+str(self.ratio_student)+" "+str(self.price_per_km)

def loadPrice():
    p = Price.objects.create(train_type='G',seat_type=u'一等座',ratio_student=0.5,price_per_km=0.775)
    p.save()
    p = Price.objects.create(train_type='G',seat_type=u'二等座',ratio_student=0.5,price_per_km=0.446)
    p.save()
    p = Price.objects.create(train_type='G',seat_type=u'商务座',ratio_student=0.5,price_per_km=0.9)
    p.save()
    p = Price.objects.create(train_type='G',seat_type=u'硬座',ratio_student=0.5,price_per_km=0.3)
    p.save()
    p = Price.objects.create(train_type='G',seat_type=u'硬卧',ratio_student=0.5,price_per_km=0.7)
    p.save()
    p = Price.objects.create(train_type='G',seat_type=u'软卧',ratio_student=0.5,price_per_km=1.4)
    p.save()

    p = Price.objects.create(train_type='D',seat_type=u'一等座',ratio_student=0.5,price_per_km=0.348)
    p.save()
    p = Price.objects.create(train_type='D',seat_type=u'二等座',ratio_student=0.5,price_per_km=0.288)
    p.save()
    p = Price.objects.create(train_type='D',seat_type=u'商务座',ratio_student=0.5,price_per_km=0.5)
    p.save()
    p = Price.objects.create(train_type='G',seat_type=u'硬座',ratio_student=0.5,price_per_km=0.18)
    p.save()
    p = Price.objects.create(train_type='D',seat_type=u'硬卧',ratio_student=0.5,price_per_km=0.4)
    p.save()
    p = Price.objects.create(train_type='D',seat_type=u'软卧',ratio_student=0.5,price_per_km=1.2)
    p.save()

    p = Price.objects.create(train_type='K',seat_type=u'一等座',ratio_student=0.5,price_per_km=0.348)
    p.save()
    p = Price.objects.create(train_type='K',seat_type=u'二等座',ratio_student=0.5,price_per_km=0.288)
    p.save()
    p = Price.objects.create(train_type='K',seat_type=u'商务座',ratio_student=0.5,price_per_km=0.5)
    p.save()
    p = Price.objects.create(train_type='K',seat_type=u'硬座',ratio_student=0.5,price_per_km=0.16)
    p.save()
    p = Price.objects.create(train_type='K',seat_type=u'硬卧',ratio_student=0.5,price_per_km=0.853)
    p.save()
    p = Price.objects.create(train_type='K',seat_type=u'软卧',ratio_student=0.5,price_per_km=1.217)
    p.save()

trainManage/views.py
# -*- encoding:utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Train, Run, Station, Carriage,Seat,TimeSpan
from .forms import *
from django.forms import formset_factory
from datetime import datetime
from datetime import datetime, timedelta
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required

span = 3 # 卖票的时间跨度
# Create your views here.
class train_ListView(PermissionRequiredMixin, ListView):
    permission_required = "trainManage.add_train"
    model = Train
    template_name = 'trainManage/train_list.html'

class train_create(PermissionRequiredMixin, CreateView):
    permission_required = "trainManage.add_train"
    model = Train
    template_name = "trainManage/train_create.html"
    success_url = "/trainManage/"
    form_class = TrainForm


    def get(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form =self.get_form(form_class)
        fileForm = trainFileForm()
        run_form = RunForm_stationSet()
        return self.render_to_response(self.get_context_data(form=form, item_form=run_form, trainFileForm=trainFileForm))

    def post(self, request, *args, **kwargs):
        print request.POST
        print RunForm_stationSet
        self.object=None
        form_class = self.get_form_class()
        form =self.get_form(form_class)
        run_form = RunForm_stationSet(request.POST)
        if (form.is_valid() and run_form.is_valid() ):
            num_station = run_form.total_form_count()
            train = form.save(commit=False)
            self.object=train
            train.num_station = num_station
            day_count = 0
            time_list = []
            distance_list = []
            print(len(run_form))
            for runForm in run_form:
                run = runForm.save(commit=False)
                distance_list.append(run.distance_count)
            train.train_type = train.train_id[0]
            train.distance = distance_list[-1]
            train.save()
            for runForm in run_form:
                run = runForm.save(commit=False)
                runCount = run.order_of_station
                #arrive_time = datetime.strptime(run.arrive_time, "%H:%M")
                arrive_time = run.arrive_time
                time_list.append(arrive_time)
                if(runCount != 1):
                    pre_arrive = time_list[runCount -1]
                    if arrive_time < pre_arrive:
                        day_count += 1
                run.count_over_night = day_count
                run.run_key = Run.generateRunKey(run.station_name.station_id, train.train_id)
                run.train_come_by = train
                run.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            print("wrong validation")
            return self.render_to_response(
                    self.get_context_data(form=form,
                        item_form=run_form))


class train_detail(PermissionRequiredMixin,DetailView):
    permission_required = "trainManage.add_train"
    model = Train
    template_name = "trainManage/train_detail.html"
    context_object_name = "train"

class train_delete(PermissionRequiredMixin, DeleteView):
    permission_required = "trainManage.add_train"
    model = Train
    template_name = "trainManage/train_confirm_delete.html"
    success_url = '/trainManage/'


class addCarriage(PermissionRequiredMixin, CreateView):
    permission_required = "trainManage.add_train"
    model = Train
    template_name = "trainManage/addCarriage.html"
    success_url = "/trainManage/"


    def get(self, request, *args, **kwargs):
        self.object = Train.objects.get(train_id = kwargs['pk'])
        carriage_form = CarriageForm()
        return self.render_to_response(self.get_context_data(form=self.object, item_form=carriage_form))

    def post(self, request, *args, **kwargs):
        print(request)
        self.object = Train.objects.get(train_id = kwargs['pk'])
        carriage_form = CarriageForm(request.POST)
        if ( carriage_form.is_valid() ):
            status = '1'*self.object.num_station
            train_id = self.object
            carriage_list = []
            seat_list = []
            timeSpan = TimeSpan.objects.all()
            for carriageform in carriage_form:
                carriage = carriageform.save(commit=False)
                carriage.train_id = self.object
                carriage.carriage_key = Carriage.generateCarriageKey(self.object.train_id, carriage.carriage_id)
                #carriage.save()
                carriage_list.append(carriage)
                if len(timeSpan) == 0:
                    timeSpan = []
                    for i in range(span):
                        date = TimeSpan(time = datetime.date(datetime.today()+ timedelta(i)))
                        timeSpan.append(date)
                    TimeSpan.objects.bulk_create(timeSpan)
                    timeSpan = TimeSpan.objects.all()
                for seat_id in range(1, carriage.num_seat+1):
                    for date in timeSpan:
                        #date = time.time
                        seat_key = Seat.generateSeatRunKey(date, carriage.carriage_key, seat_id)
                        print(seat_key)
                        seat = Seat(seat_key = seat_key,
                                    carriage=carriage,
                                    seat_id = seat_id,
                                    date=date,
                                    status=status)
                        print("nothing wrong here")
                        #seat.save()
                        seat_list.append(seat)
            Carriage.objects.bulk_create(carriage_list)
            Seat.objects.bulk_create(seat_list)
            return HttpResponseRedirect(self.get_success_url())
        else:
            print("wrong validation")
            return self.render_to_response(
                self.get_context_data(form=self.object,
                                      item_form=carriage_form))


@permission_required('trainManage.delete_timespan')
def updateSeat(request):
    timeSpan = 10
    date_list = []
    dateList = [] # reload date beyond exist_list
    newSeat_list = []
    exist_list = TimeSpan.objects.all()
    for date in exist_list:
        if  (datetime.date(datetime.today()) - date.time).days > 30:
            TimeSpan.delete(date)
    try:
        Seat_list = exist_list[0].seat_set.all()
    except:
        return HttpResponse('there is no seat to update')
    for i in range(timeSpan):
        date_list.append(TimeSpan(time=datetime.date(datetime.now() +timedelta(i))))
    if exist_list[0].time == datetime.date(datetime.today()) and len(exist_list)==len(date_list):
        return HttpResponse('no need to update')
    for date in date_list:
        if date not in exist_list:
            dateList.append(date)
            for seat in Seat_list:
                seat_key = seat.seat_key
                tmp_key = list(seat_key)
                tmp_key[7:15] = date.time.strftime("%Y%m%d")
                seat_key = ''.join(tmp_key)
                status = seat.status
                status = '1' * len(status)
                newSeat = Seat(seat_key = seat_key,
                            carriage=seat.carriage,
                            seat_id = seat.seat_id,
                            date=date,
                            status=status)
                newSeat_list.append(newSeat)
    try:
        TimeSpan.objects.bulk_create(dateList)
        Seat.objects.bulk_create(newSeat_list)
    except:
        return HttpResponse("wrong with something, please check the database")
    return HttpResponse("Done with update")



def trainCreateFromFile(request):
    if request.method == "POST":
        file = request.FILES['file']
        ex_order = 0
        distance_list = []
        station_list = []
        arrive_time_list = []
        ex_train = ''
        train_list =[]
        run_list = []
        for line in  request.FILES['file']:
            try:
                train_id, order, station_name, arrive_time, distance = line.strip().split("\t")
            except:
                return HttpResponse("Wrong file")
            order = int(order)
            distance = float(distance)
            day_count  = 0
            if  ex_order < order:
                ex_train = train_id
                ex_order = order
                distance_list.append(distance)
                try:
                    station_list.append(Station.objects.get(station_name = station_name))
                except:
                    print station_name
                    return HttpResponseRedirect("/")
                arrive_time_list.append(arrive_time)
            else:
                train = Train()
                train.distance = distance_list[-1]
                train.train_id = ex_train
                train.train_type = train_id[0]
                train.num_station = ex_order
                #train.save()
                train_list.append(train)
                for i in range(ex_order):
                    run = Run()
                    runCount = i+1;
                    if(runCount != 1):
                        pre_arrive = arrive_time_list[runCount -1]
                        if arrive_time < pre_arrive:
                            day_count += 1
                    run.count_over_night = day_count
                    run.run_key = Run.generateRunKey(station_list[i].station_id, train.train_id)
                    run.order_of_station = runCount
                    run.station_name = station_list[i]

templates/trainManage/addCarriage.html
{% extends "base.html" %}

{% block content %}
<html lang="zh-CN">
<head>    
    <title>添加座位</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="style.css">
    <style>
    .table th{
        text-align: center;
        background-color: #39f;
        font-weight:bold;
        color: #fff;
    }
    #table_title{     
        width: 60%; 
        font-size:18px;
        background-color:#eee;
        margin-top: 25px;
        padding-top: 5px;
        padding-bottom: 5px;
   
    } 
    #table_content td{
        text-align: center;
        vertical-align:middle;
    }
    
    #search_inside{     
        text-align:center;
        margin:0 auto;
        height: 100px;
        margin-top: 25px;
    } 

    #search_result{     
        text-align:center;
        padding-bottom: 0px;
        width: 60%; 
        padding-left: 0px;
        padding-right: 0px;
    }  
    #title_right{     
        float:right;
    } 
    #leftbutton{     
        float:left;
    } 
    #rightbutton{   
        float:right;
        margin-bottom: 60px;
    } 

    </style>
                        
</head>     
    <script src="/static/js/jquery-2.0.3.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>

<form method="post">{% csrf_token %}

    {{ item_form.management_form }}
    {{ item_form.non_form_erros }}

    <div class="container"  id="table_title">
        <span class="glyphicon glyphicon-plus-sign"> 添加座位</span>
        <span id="title_right">列车编号:{{ form.train_id }}</span>
    </div>

    <div class="container" id="search_result">
        <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr id="table_content">
            <th> 车厢编号 </th>
            <th> 座位数 </th>
            <th> 座位类型 </th>
            <th> 备注 </th>
            </tr>
        </thead>
        {% for form in item_form %}
            <p style="display:none">{{form.DELETE}}</p>
            <tbody class="item">
                <tr>
                <td> {{form.carriage_id}}</td>
                <td> {{form.num_seat}} </td>
                <td> {{form.seat_type}} </td>
                <td><button type="button" name="delete" class="btn btn-danger btn-lg" style="font-size:14px" > 删除 <span class="glyphicon glyphicon-remove"></span></button></td>
                </tr>
        {% endfor %}
            </tbody>
        </table>
        <div class="" id="leftbutton"><button type="button" class="btn btn glyphicon glyphicon-chevron-left" style="font-size:16px" onclick="window.location.href='/trainManage/'">返回列表</button><span>&nbsp&nbsp</span>
        <button type="button" id="add" class="btn btn-info glyphicon glyphicon-plus" style="font-size:16px">新增车厢</button></div>

        <div class="" id="rightbutton"><button type="submit" class="btn btn-warning btn-lg" style="font-size:16px" >确认提交 <span class="glyphicon glyphicon-ok" ></span></button></div>    
    </div>
</form>

<script type="text/javascript" src='/static/addCarriage.js'>
</script>
{% endblock %}

templates/trainManage/base.html
<!DOCTYPE html>
<html lang="zh-CN">
	<head>
		<meta charset="utf-8">
		<link href="/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
	<style>
	.nav{
        height: 0px;
    }
    .body{
        height: 100%;
    }
    #pill{
        margin-top: 5px;
        position: relative;
    }
	#footer{     
        vertical-align:middle; 
        text-align: center; 
        margin: 0px auto;
        position: absolute;
        bottom: 3px;
        width: 100%;
    }
    #right{     
        margin-right: 0px;
    } 
    #welcome{     
        margin-top: 10px;
    } 
    </style>
	</head>
		<script src="/static/js/jquery-2.0.3.js"></script>
		<script src="/static/js/bootstrap.min.js"></script>
	<body>
		<nav class="navbar navbar-default" role="navigation" class="nav">
    		<div class="navbar-header"><a class="navbar-brand" href="#">火车票服务</a>
    		</div>
    <div>
        <ul class="nav nav-pills" id="pill">
        	{% block nav %}		        
            {% endblock %} 
        </ul>
        <!--if sign in-->
         <ul class="nav nav-pills navbar-right" id="right">         
            <li id="welcome">欢迎,</li>  
            <li><a href="#">admin</a></li>    
            <li id="welcome">|</li>  
            <li><a href="#">退出登录</a></li>   <!--sign out-->
        </ul>
        <!--if not sign in-->
        <!--
         <ul class="nav nav-pills navbar-right" id="right">         
            <li id="welcome">您好,请</li>  
            <li><a href="#">登录</a></li>    
            <li id="welcome">|</li>  
            <li><a href="#">注册</a></li>   
        </ul>-->
    </div>
    </nav> 
		{% block content %}
		{% endblock %}
	</body>
	    <nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
        <div id="footer" > 
        <footer>
            版权所有 © 2016-2020 中山大学 数据科学与计算机学院</br>
            李友 李弘艺 袁陶希
        </footer>  
        </div>
    </nav> 
</html>

templates/trainManage/train_confirm_delete.html
<html lang="zh-CN">
<head>    
    <title>删除车次</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="style.css">
    <style>
	#base{
		position:fixed;
		width:30%;
		height:30%;
		top:0;
		right:0;
		bottom:0;
		left:0;
		margin:auto;
	    font-size: 20px;
	    font-weight: bold;
        text-align: center;
	}
    </style>
                        
</head>     
    <script src="/static/js/jquery-2.0.3.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>


<body>
	<div class="container" id="base">
	<form action="" method="post">{% csrf_token %}
		<p>确定要删除列车 {{ object }} 所有信息么?</p>
		 <div class="" id="rightbutton"><button type="submit" class="btn btn-danger btn-lg" style="font-size:16px" >确定<span class="glyphicon glyphicon-ok" ></span></button></div>   
	</form>
	</div>
</body>

templates/trainManage/train_detail.html
{% extends "base.html" %}

{% block content %}
<html lang="zh-CN">
<head>    
    <title>车次信息</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="style.css">
    <style>
    .table th{
        text-align: center;
        background-color: #39f;
        font-weight:bold;
        color: #fff;
    }
    #table_title{     
        width: 60%; 
        font-size:18px;
        background-color:#eee;
        margin-top: 25px;
        padding-top: 5px;
        padding-bottom: 5px;
   
    } 
    #table_content td{
        text-align: center;
        vertical-align:middle;
    }
    
    #search_inside{     
        text-align:center;
        margin:0 auto;
        height: 100px;
        margin-top: 25px;
    } 

    #search_result{     
        text-align:center;
        padding-bottom: 0px;
        width: 60%; 
        padding-left: 0px;
        padding-right: 0px;
    }  
    #title_right{     
        float:right;
    } 
    #leftbutton{     
        float:left;
    } 
    #rightbutton{   
        float:right;
        margin-bottom: 60px;
    } 

    </style>
                        
</head>     
    <script src="/static/js/jquery-2.0.3.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>

    <div class="container"  id="table_title">
        <span class="glyphicon glyphicon-map-marker">{{ train.train_id }}途经车站</span>
        <span id="title_right">总站点数:{{train.num_station}}</span>
    </div>

    <div class="container" id="search_result">
        <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th> 序号 </th>
                <th> 车站名 </th>
                <th> 到站时间 </th>
                <th> 里程数 </th>
            </tr>
        </thead>
        {% for form in train.run_set.all %}
        <tbody class="item">
            <tr id="table_content">
            <td> {{form.order_of_station}}</td>
            <td> {{form.station_name}} </td>
            <td> {{form.arrive_time|date:"H:i"}} </td>
            <td> {{form.distance_count}}</td>
            </tr>
        {% endfor %}
        </tbody>

        </table>
    </div>

    <div class="container"  id="table_title">
        <span class="glyphicon glyphicon-inbox">座位信息</span>
    </div>

    <div class="container" id="search_result">
        <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th> 车厢号 </th>
                <th> 座位总数 </th>
                <th> 座位类型 </th>
            </tr>
        </thead>
        {% for form in train.carriage_set.all %}
        <tbody class="item">
            <tr id="table_content">
            <td> {{form.carriage_id}}</td>
            <td> {{form.num_seat}}</td>
            <td> {{form.get_seat_type_display}}</td>
            </tr>
        {% endfor %}
        </tbody>
        </table>
        <div class="" id="leftbutton"><button type="button" class="btn btn glyphicon glyphicon-chevron-left" style="font-size:16px" onclick="window.location.href='/trainManage/'">返回列表</button></div>

        <div class="" id="rightbutton"><button type="button" class="btn btn-primary btn-lg" style="font-size:16px" onclick="window.location.href='/trainManage/addCarriage/{{train.train_id}}'">添加座位 <span class="glyphicon glyphicon-plus" ></span></button></div>   
    </div>

<script type="text/javascript" src='/static/modify.js'>
</script>
{% endblock %}