lylTicket/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import *

urlpatterns = [
    url(r'^$', index),
    url(r'^admin/', admin.site.urls),
    url(r'^trainManage/', include('trainManage.urls')),
    url(r'^ticketQuery/', include("ticketQuery.urls")),
    url(r'^accounts/', include('userClass.urls')),
    url(r'^addPassenger/',include('addPassenger.urls')),

]

ticketQuery/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', ticketQuery.as_view(), name = "ticket_query"),
    url(r'^order/$', ticketOrder.as_view(), name="ticket_order"),
    url(r'^order/orderconfirm/$', ticketOrderConfirm.as_view(), name="ticket_order_confirm"),
    url(r'^order/ordercompleted/$', ticketOrderCompleted.as_view(), name="ticket_order_completed"),
]

addPassenger/models.py
#-*- coding:utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Passenger(models.Model):
    passenger_name = models.CharField('乘车人姓名',max_length=20)
    passenger_id = models.CharField('身份证号码',max_length=20,primary_key=True)
    student = models.IntegerField('学生票',default=0)
    users = models.ManyToManyField(User)

    def __str__(self):
        return self.passenger_id

    def __unicode__(self):
    	return self.passenger_id

ticketQuery/models.py
#-*-coding:utf-8-*-
from __future__ import unicode_literals

from django.db import models

from trainManage.models import Train,Station,Seat

# Create your models here.

class Order(models.Model):
    order_id = models.CharField('订单编号',max_length=20,primary_key=True)
    user_name = models.CharField('用户名',max_length=20)
    passenger_name = models.CharField('乘客姓名',max_length=20)
    passenger_id = models.CharField('乘客身份证号',max_length=20)
    passenger_phone = models.CharField('电话',max_length=10)
    student = models.IntegerField('学生票',default=0)
    order_time = models.DateTimeField('订票时间')
    train_name = models.ForeignKey(Train, on_delete=models.CASCADE)
    start_station = models.ForeignKey(Station,on_delete=models.CASCADE,related_name='start_station')
    end_station = models.ForeignKey(Station,on_delete=models.CASCADE,related_name='end_station')
    trip_date = models.DateTimeField('出发日期')
    seat = models.ForeignKey(Seat, on_delete=models.CASCADE)
    pay = models.FloatField('金额',default = 0)
    order_status = models.IntegerField('订单状态',default=0) #0 train does not go;1 order is completed ; 2 order is canceled 

    def __str__(self):
        return self.order_id

    def __unicode__(self):
        return self.order_id

ticketQuery/forms.py
from django import forms
from django.forms import  inlineformset_factory,modelformset_factory,formset_factory
from trainManage.models import Station

class TicketQueryForm(forms.Form):
#    def __init__(self):
#        super(TicketQueryForm,self).__init__()
#        self.fields['startStation'].choices = ['--------'] +\
#            [station.station_name for station in Station.objects.all()]
#        self.fields['endStation'].choices = ['--------'] +\
#            [station.station_name for station in Station.objects.all()]
#    startStation = forms.ChoiceField(choices=(), required=True, widget=forms.Select())
#    endStation = forms.ChoiceField(choices=(), required=True, widget=forms.Select())
    startStation = forms.ModelChoiceField(queryset=Station.objects.all(), required=True)
    endStation = forms.ModelChoiceField(queryset=Station.objects.all(), required=True)
    date = forms.DateField(required=True, widget=forms.DateInput())


class QueryResultForm(forms.Form):
    startStation = forms.ModelChoiceField(queryset=Station.objects.all(), required=True)
    endStation = forms.ModelChoiceField(queryset=Station.objects.all(), required=True)
    date = forms.DateField(required=True, widget=forms.DateInput())


#class PassengerInfoForm(forms.Form):


class PassengerInfoForm(forms.Form):
    order = forms.IntegerField(widget=forms.TextInput(attrs={'readonly':'readonly', 'value':1}))
    seat_type = forms.CharField()
    student = forms.IntegerField()
    passenger_name = forms.CharField()
    passenger_id = forms.CharField()
    passenger_phone = forms.CharField()
    
PassengerInfoFormSet = formset_factory(PassengerInfoForm,max_num=10,extra=1)

ticketQuery/views.py
# -*- coding:utf-8 -*-
from django.shortcuts import render, render_to_response
#from django.views.generic import View
from django.views.generic.base import TemplateView
from .forms import *
from trainManage.models import *
from ticketQuery.models import *
from datetime import datetime, timedelta
from django.contrib.auth.mixins import LoginRequiredMixin
from collections import OrderedDict
#from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User,Group
from django.contrib.sessions.models import Session
from django.http import HttpResponse, HttpResponseRedirect




def get_currentUser(request):
    s = Session.objects.get(pk=request.COOKIES['sessionid'])
    #print s.expire_date
    #print s.get_decoded()['_auth_user_id']
    user_id = s.get_decoded()['_auth_user_id']
    user = User.objects.get(id=user_id)
    return user




# Create your views here.
class ticketQuery(TemplateView):
    form_class = TicketQueryForm
    template_name = "ticketQuery/ticket_query.html"
    def get(self, request, *args, **kwargs):
        form = TicketQueryForm()
        return self.render_to_response(self.get_context_data(form=form))

    def post(self, request, *args, **kwargs):
        request.session['test'] = False;
        form = self.form_class(request.POST)
        startStationID = request.POST['startStation']
        startStation = Station.objects.get(station_id=startStationID)
        endStationID = request.POST['endStation']
        endStation = Station.objects.get(station_id=endStationID)
        date =  datetime.strptime(request.POST['date'], "%m/%d/%Y")
        date = datetime.date(date)
        query = Query(startStation, endStation, TimeSpan(time=date))
        print('below here')
        resultSet= query.search()
        print('below here')
        #print resultSet
        return self.render_to_response(self.get_context_data(form=form,
                                                             startStation=startStation,
                                                             endStation=endStation,
                                                             date = date,
                                                             resultSet=resultSet,
                                                             ))

class ticketOrder(LoginRequiredMixin,TemplateView):
    template_name = "ticketQuery/ticket_order.html"
    def post(self, request):
        # rebuild the result to a dictionary which store the result
        seat_type_to_seat_key = {}
        train_id = request.POST['train_id']
        seat_type_dict = {'shangwu': '商务座',
        'yideng': '一等座',
        'erdeng': '二等座',
        'ruanwo': '软卧',
        'yingwo': '硬卧',
        'yingzuo': '硬座',
        }
        start = request.POST['start']
        end = request.POST['end']
        date = request.POST['date']
        date = datetime.date(datetime.strptime(date, "%b. %d, %Y"))
        print(request.POST)
        print(request.session.keys())
        seat_type_num = request.POST['seat_type_num']
        for i in range(1, int(seat_type_num)+1):
            seat_type_index = "seat_type_" + str(i)
            try:
                seat_type = request.POST[seat_type_index]
                seat_type_counter_index = seat_type + "_counter"
                seat_type_counter = request.POST[seat_type_counter_index]
                for j in range(1, int(seat_type_counter)+1):
                    seat_index = seat_type +"_" + str(j)
                    seat_key = request.POST[seat_index]
                    seat_key_set = seat_type_to_seat_key.setdefault(seat_type_dict[seat_type], [])
                    seat_key_set.append(seat_key)
            except:
                pass
        user = get_currentUser(request)
        passenger_set = user.passenger_set.all()
        for p in passenger_set:
            print p.passenger_name
        #print seat_type_to_seat_key
        form_set = PassengerInfoFormSet()
        # they are all strings , not objects
        return self.render_to_response(self.get_context_data(seat_type_to_seat_key=seat_type_to_seat_key,
                                                             train_id = train_id,
                                                             date=date,
                                                             start=start,
                                                             end = end,
                                                             passenger_set=passenger_set,
                                                             form_set=form_set))

# This is a class for search process
class Query(object):
    def __init__(self, start, end, date):
        self.start =  start
        self.end = end
        self.date = date
        self.delay = 30 # the time you can order ticket before the
    def search(self):
        #resultSet = {train_id:{seat_type:[seat_key]}}
        resultSet = {}
        startSet = set()
        endSet = set()
        for run in self.start.run_set.all():
            startSet.add(run.train_come_by)
        for run in self.end.run_set.all():
            endSet.add(run.train_come_by)
        trainSet = startSet & endSet
        trainStartTime = {}

        for train in trainSet:
            startRun = Run.objects.get(train_come_by= train, station_name=self.start)
            endRun = Run.objects.get(train_come_by=train, station_name=self.end)
            startOrder = startRun.order_of_station
            endOrder = endRun.order_of_station
            today = datetime.date(datetime.today())
            startDate = self.date.time - timedelta(startRun.count_over_night) # the start date of train
            if today< self.date.time or ( today==self.date.time and datetime.time(datetime.now()) < startRun.arrive_time): # before train arrive
            # input time must later than now
                if  startOrder < endOrder:
                    arrive_time = \
                        train.run_set.get(train_come_by=train,station_name=self.start).arrive_time
                    resultSet[train.train_id] = {'yideng':[],'erdeng':[],'shangwu':[],'ruanwo':[],
                                                 'yingzuo':[],'yingzuo':[], "arrive_time":arrive_time}
                    trainStartTime[train.train_id]= \
                        train.run_set.get(train_come_by=train,station_name=self.start).arrive_time
                    for carriage in train.carriage_set.all():
                        seatSet = carriage.seat_set.all()
                        seatSet = seatSet.filter(date=TimeSpan(time=startDate))
                        for seat in seatSet:
                            if seat.status[startOrder-1:endOrder][:-1] == "1" *(endOrder-startOrder):
                                type_seat = resultSet.setdefault(train.train_id,{})
                                seat_result = type_seat.setdefault(seat.carriage.seat_type,[])
                                seat_result.append(seat)
        
        resultSet = OrderedDict(sorted(resultSet.iteritems(), key=lambda x:x[1]['arrive_time']))
        return resultSet


class ticketOrderConfirm(TemplateView, LoginRequiredMixin):
    template_name = "ticketQuery/ticket_order_confirm.html"
    def post(self, request):
        print request.POST
        order_id = '111111'
        total_forms = request.POST['form-TOTAL_FORMS']
        print "total_forms = " + total_forms
        print int(total_forms)

        total_passenger = request.POST['total_passenger']
        print "total_passenger = " + total_passenger

        seat_counter = {}
        seat_used_counter = {}
        seat_type_num = request.POST['seat_type_num']
        print "-------------seat_type information-------------"
        for i in range(1, int(seat_type_num)+1):
            seat_type_index = "seat_type_" + str(i)
            try:
                seat_type = request.POST[seat_type_index]
                seat_type_counter_index = seat_type + "_counter"
                seat_type_counter = request.POST[seat_type_counter_index]
                seat_counter[seat_type] = int(seat_type_counter)
                seat_used_counter[seat_type] = 0
                print 'seat_type: ' + seat_type + ' seat_type_counter:' + str(seat_counter[seat_type])
                print 'seat_type: ' + seat_type + ' seat_used_counter:' + str(seat_used_counter[seat_type])
            except:
                pass
        print "-------------seat_type information-------------"
        '''
        yideng_counter = request.POST[u'一等座_counter']
        erdeng_counter = request.POST[u'二等座_counter']
        shangwu_counter = request.POST[u'商务座_counter']
        yingzuo_counter = request.POST[u'硬座_counter']
        yingwo_counter = request.POST[u'硬卧_counter']
        ruanwo_counter = request.POST[u'软卧_counter']

        seat_counter = {u'一等座':int(yideng_counter),u'二等座':int(erdeng_counter),u'商务座':int(shangwu_counter),\
                        u'硬座':int(yingzuo_counter),u'硬卧':int(yingwo_counter),u'软卧':int(ruanwo_counter)}

        '''
        '''
        seat1 = Seat.objects.get(seat_key=seat_key_1[2:])
        print "---------------seat information----------------  "
        print seat1.carriage.train_id,seat1.carriage.carriage_id,seat1.seat_id,seat1.carriage.seat_type,seat1.date,seat1.status
        print "---------------seat information----------------  "
        '''
        #process each passenger
        passenger_info_list = []
        seat_list = []
        '''
        seat_used_counter = {u'一等座':0,u'二等座':0,u'商务座':0,\
                        u'硬座':0,u'硬卧':0,u'软卧':0}
        '''
        for i in xrange(0,int(total_forms)):
            key_order = "form-%d-order" % i
            key_seattype = "form-%d-seat_type" % i
            key_student = "form-%d-student" % i
            key_name = "form-%d-passenger_name" % i
            key_id = "form-%d-passenger_id" % i
            key_phone = "form-%d-passenger_phone" % i

templates/ticketQuery/ticket_buy.html
{% extends "base1.html" %}

{% block content %}
<html lang="zh-CN">
<head>
    <title>车票购买</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="style.css">
    <style>
    .table th{
        text-align: center;
        background-color: #39f;
        font-weight:bold;
        color: #fff;
    }
    #table_content td{
        text-align: center;
        vertical-align:middle;
    }

    #order_warning{     
        border: 1px solid #09f;
        border-radius: 10px;
        width: 60%; 
        background-color:#eee;
        height: 100px;
    } 
    #order_warning_content{   
        vertical-align: center;
        margin-top: 35px;
        text-align: center;
        font-size: 18px;
        font-weight:bold;
    } 

    #order_info{    
        width: 60%;
        margin: 20px auto;
    } 
    #order_info_title{     
        font-size:18px;
        background-color:#eee;
        padding-top: 5px; 
        padding-bottom: 5px;
        padding-left: 10px;
        border-bottom: 2px solid #bbb;
    } 
    #order_info_date{     
        font-weight:bold;
        font-size:18px;
        background-color:#eee;
        padding-top: 5px;
        padding-bottom: 3px; 
        padding-left: 15px;
    } 

    #thirty{     
        font-size: 22px;
        color:#F90;
    }
    #clock{     
        font-size: 22px;
        color:#F90;
    }
    #buy{     
        text-align: center;
    } 
    </style>

    <script src="/static/js/jquery-2.0.3.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>

    <script>  var x = 30,
            interval;
        window.onload = function() {
            var d = new Date("1111/1/1,0:" + x + ":0");
            interval = setInterval(function() {
                var m = d.getMinutes();
                var s = d.getSeconds();
                m = m < 10 ? "0" + m : m;
                s = s < 10 ? "0" + s : s;
                clock.innerHTML = m + ":" + s;
                if (m == 0 && s == 0) {
                    clearInterval(interval);
                    return;
                }
                d.setSeconds(s - 1);
            }, 1000);
        }
        </script>                   
</head>     

    <div class="container" id="order_warning" >
        <div class="" id="order_warning_content">
            <span class="glyphicon glyphicon glyphicon-lock" >&nbsp</span><span>席位已锁定，请在<span id="thirty">30</span>分钟内进行支付，完成网上购票。支付剩余时间：<span id="clock"></span></span>
        </div>
    </div>

    <div class="" id="order_info">
        <form method="post">{% csrf_token %}
            <div class=""  id="order_info_title">
                <span class="glyphicon glyphicon-book">订单信息</span>
            </div>
            <div class="">
                <div class="" id="order_info_date">
                    <span> {{date.year}}2016年{{date.month}}12月{{date.day}}10日</span>
                    <span>{{train_id}}G1234</span>次
                    <span>{{start}}</span><span>广州站</span><span>——</span><span>{{end}}</sapn><span>北京站</span>
                </div>
                <table class = "table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th> 序号 </th>
                            <th> 姓名 </th>
                            <th> 身份证号码 </th> 
                            <th> 票种 </th>
                            <th> 席别 </th>
                            <th> 车厢 </th>
                            <th> 座位号 </th>
                            <th> 票价(元) </th>
                        </tr>
                    </thead>
                    <p style="display:none">{{form.DELETE}}</p>
                    <tbody class="item">
                        <form class="bs-example bs-example-form" role="form">
                        <tr id="table_content">
                            <td> 1 </td>
                            <td> user name </td>
                            <td> id number </td>
                            <td> student </td>
                            <td> second seat </td>
                            <td> carriage number 01 </td>
                            <td> seat number 05F </td>
                            <td> ticket price 234.5 </td>
                        </tr>
                        </form>
                    </tbody>        
                </table>
            </div>

            <div class="" id="buy">
                <button type="button" class="btn btn-danger btn-lg" style="font-size:16px" onclick="window.location.href='#'">取消订单<span class="glyphicon glyphicon-remove"></span></button><span>&nbsp&nbsp</span>
                <button type="submit" class="btn btn-warning btn-lg" style="font-size:16px" onclick="window.location.href='#'">&nbsp去支付&nbsp<span class="glyphicon glyphicon-chevron-right"></span></button>
            </div>
        </form>
    </div>

<script type="text/javascript" src='/static/modify.js'>
</script>
{% endblock %}

templates/ticketQuery/ticket_order_completed.html
{% extends "base.html" %}
{% block content %}
<p>{{ response }}</p>
<a href="/accounts/personinfo" type="button">返回个人中心</a>
{% endblock %}

templates/ticketQuery/ticket_query.html
{% extends "base.html" %}

{% block content %}
<html lang="zh-CN">
<head>
    <title>车票查询</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link href="/static/css/select2.min.css" rel="stylesheet" media="screen">
    <link href="/static/css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">
    <style>
    .table{
        margin-bottom: 0px;
    }
    .table th{
        text-align: center;
        background-color: #39f;
        font-weight:bold;
        color: #fff;
    }
    #table_title{
        margin-top: 25px;
        text-align: left;
        font-weight:bold;
        font-size:17px;
    }
    #table_content td{
        text-align: center;
        vertical-align:middle;
    }
    
    #search_info{     
        border: 1px solid #09f;
        border-radius: 25px;
        text-align:center;
        margin:0 auto;
        height: 100px;
        width: 80%;
        background-color:#eee;
    }
    #search_inside{
        text-align:center;
        margin:0 auto;
        height: 100px;
        margin-top: 28px;
    }

    #search_result{
        text-align:center;
        width: 80%;
        margin: 10px auto;  
    }
    </style>
</head>

<script type="text/javascript">
    $(function(){
    $("#id_startStation").select2({
        templateSelection : function(selection) {
            return $.trim(selection.text);
        }
    });
    $("#id_endStation").select2({
        templateSelection : function(selection) {
            return $.trim(selection.text);
        }
    });
    validateTalentInfoForm();
    })
</script>


    <div class="container" id="search_info" >
        <form method="post"> {% csrf_token %}
        <div  class="" id="search_inside">
            <span class="label label-info glyphicon glyphicon-map-marker" style="font-size:16px ">&nbsp出发地&nbsp</span><span>{{form.startStation}}</span>&nbsp&nbsp&nbsp&nbsp
            <span class="label label-info glyphicon glyphicon-map-marker" style="font-size:16px ">&nbsp目的地&nbsp</span><span>{{form.endStation}}</span>&nbsp&nbsp&nbsp&nbsp
            <span class="label label-info glyphicon glyphicon-calendar" style="font-size:16px ">&nbsp出发时间&nbsp</span><span>{{form.date}} {{form.date.errors}}</span>&nbsp&nbsp&nbsp&nbsp         
            <button type="submit" class="btn btn-warning btn-lg glyphicon glyphicon-search" style="font-size:18px">&nbsp&nbsp查询&nbsp&nbsp</button>
        </div>
        </form>
    </div>
    {% if resultSet %}
    <div class="" id="search_result">
        <div id="table_title">
            {{date.year}}年{{date.month}}月{{date.day}}日&nbsp&nbsp&nbsp{{ startStation.station_name }} ——> {{ endStation.station_name}}
        </div>
        <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>车次</th>
                <th>出发站</th>
                <th>到达站</th>
                <th>出发时间</th>
                <th>商务座</th>
                <th>一等座</th>
                <th>二等座</th>
                <th>软卧</th>
                <th>硬卧</th>
                <th>硬座</th>
                <th>备注</th>
            </tr>
        </thead>
        <tbody>            
        {% for train_id, type_seat in resultSet.iteritems %}
            <form method="post" action="/ticketQuery/order/">{% csrf_token %}
                <tr id="table_content">
                    <input type="hidden" value="{{startStation.station_name}}" name="start"/>
                    <input type="hidden" value="{{endStation.station_name}}" name="end"/>
                    <input type="hidden" value="{{date}}" name="date"/>
                    <td> {{ train_id }}</td>
                    <td> {{ startStation.station_name }}</td>
                    <td> {{ endStation.station_name }}</td>
                    <td> {{ type_seat.arrive_time |date:"H:i"}}</td>
                    <input type="hidden" value="{{train_id}}" name="train_id"/>
                    <td> {{ type_seat.shangwu|length }}</td>
                    <td> {{ type_seat.yideng|length }}</td>
                    <td> {{ type_seat.erdeng|length}}</td>
                    <td> {{ type_seat.ruanwo|length}}</td>
                    <td> {{ type_seat.yingwo|length}}</td>
                    <td> {{ type_seat.yingzuo|length}}</td>
                    {% for type ,seatSet in type_seat.iteritems %}
                    <!--<td> {{ seatSet|length }}</td> -->
                    {% ifnotequal type  "arrive_time" %}
                            {% for seat in seatSet %}
                                <input name="{{type}}_{{forloop.counter}}" value=" {{seat.seat_key}}" type="hidden"/>
                                <input type="hidden" value= {{forloop.counter}} name="{{type}}_counter"/>
                            {% endfor %}
                            <input type="hidden" value="{{ type_seat.arrive_time }}" name="arrive_time"/>
                            <input type="hidden" value={{type}} name="seat_type_{{forloop.counter}}"/>
                            <input type="hidden" value={{forloop.counter}} name="seat_type_num"/>
                    {% endifnotequal %}
                    {% endfor %}
                    {% if type_seat.shangwu|length or type_seat.yideng|length or type_seat.erdeng|length or type_seat.ruanwo|length or type_seat.yingwo|length or type_seat.yingzuo|length %}
                        {% if user.is_authenticated %}
                        <td><button type="submit" name="order" class="btn btn-primary btn-lg " style="font-size:16px"> 预订 <span class="glyphicon glyphicon-pushpin"></span></button></td>
                        {% endif %}
                    {% else %}
                        <td><button type="submit" name="order" class="btn btn-lg " style="font-size:16px" disabled="disabled"> 预订 <span class="glyphicon glyphicon-pushpin"></span></button></td>
                    {% endif %}
                    </tr>
            </form>
        {% endfor %}
        </tbody>
        </table>
    </div>
    {% endif %}

<script src="/static/js/jquery-2.0.3.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/select2.min.js"></script>
<script src="/static/js/bootstrap-datetimepicker.min.js"></script>
<script src="/static/js/bootstrap-datetimepicker.zh-CN.js"></script>
<script type="text/javascript">
var nowTemp = new Date();
    var now = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate(), 0, 0, 0, 0);
    var end = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate()+30, 0, 0, 0, 0);
    $('#id_date').datetimepicker({
        format:'mm/dd/yyyy',
        language:  'zh-CN',
        todayBtn:  1,
        autoclose: 1,
        todayHighlight: 1,
        startView: 2,
        minView: 2,
        forceParse: 0,
        startDate:now,
        endDate:end,
    });

</script>
{% endblock %}  